project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023" 
    right: 
      - icon: github
        href: https://github.com/JulianGorman
  title: "Website -- Julian Gorman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Portfolio
        href: portfolio.qmd
      - text: Walkthrough
        href: walkthrough.qmd
      - text: Writing Examples
        menu:
        - text: Malaria Research
          href: paper.qmd
        - text: Debate Story
          href: media.qmd
      - text: VA Project
        menu:
        - text: VA Data
          href: vaprojectdata.qmd
        - text: VA Analysis
          href: vaprojectanalysis.qmd
      - gaincome.qmd

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



