---
title: "Debate Story"
editor: visual
---

### **Murphy, Ciattarrelli face off in raucous final debate**

Tuesday night's New Jersey gubernatorial debate was perhaps a David and Goliath-esque battle as Republican nominee Jack Ciattarelli engaged in a contested bout with incumbent Gov. Phil Murphy. The discordant yet slightly cordial banter exchanged between the two candidates was often interrupted by a rowdy audience. The debate, which occurred on October 12, 2021, was held at Rowan University in Glassboro, New Jersey. The four moderators for the final debate before voters head to the polls were David Cruz, who is serving as senior political correspondent at NJ Spotlight News; Ben Dworkin, the founding director of the Rowan Institute for Public Policy and Citizenship; Michael Hill, host of WNYC's Morning Edition, and Colleen O'Dea, who is NJ Spotlight News' senior writer and projects editor.

Ciattarelli voiced heavy criticism for the Murphy Administration early during the debate. Ciattarelli said, "I believe that the state government is bloated, inefficient, and corrupted by certain special interests, including those that have given the governor more than ten million dollars over the past five years." Murphy countered Ciattarelli's attacks by citing that his Administration has actually cut jobs in New Jersey's state government during his time in office. Murphy then referenced Ciattarelli's potential ties to Trump and the GOP. When speaking about Ciattarelli's policy on illegal immigration, Murphy said, "we gotta get away from this Trump 'Us vs. Them' stuff, we're all in the state together." When Ciattarelli was asked by a moderator about his past endorsements of Trump, he said that he believes Trump had many successes while in office; however, he disagrees with him in many areas regarding New Jersey.

On COVID and recovery efforts, Ciattarelli was questioned on his opposition to vaccine and mask mandates. He responded, "I think when times are as challenging as these, and I never said the pandemic was easy, it's better to adopt a policy that works for the majority of people as opposed to a heavy-handed, one sized fits all approach." Ciattarelli then threw a jab at Murphy by accusing him of attending a large indoor conference while maskless. Murphy said that he is always in accordance with the CDC guidance in regards to masking. On economic recovery efforts in the state, Murphy continuously cited his Administration's dedication to funding and assistance to small businesses throughout the pandemic, including a \$780 million allocation to small businesses. Murphy said, "we've thrown a ton of money at small businesses, only California and New York have put more towards small businesses." Ciattarelli argued that Murphy's Administration has not done enough, referencing a recent study showing that there are 276,000 fewer jobs in New Jersey than before the pandemic. Ciattarelli criticized Murphy's unemployment benefits and eviction moratorium, stating that they were too generous.

Controversy also arose over crime and policing in the state. Murphy stated that he has multiple endorsements from police endorsements and that Ciattarelli has none. Murphy said that his Administration has readdressed the use of force in policing and has funded two police training programs within the state. Ciattarelli argued that the endorsements were from four years ago and that Murphy is not currently endorsed by the unions.

On abortion, Murphy voiced concern that women's rights would be compromised by Supreme Court decisions regarding Roe V. Wade. He said, "With the now not abstract or theoretical likelihood that Roe V. Wade is at a minimum impaired if not completely stripped we must take action." Ciattarelli said that he supports Roe V. Wade and the right of a woman to choose; however, he wants to establish bans on abortions during months seven, eight, and nine of the pregnancy. He quipped that support of abortions during these months is "extremism, that's not New Jersey, that's Phil Murphy."

In closing, Ciattarrelli said that he wanted to lower property taxes by adopting a new school funding formula, create new jobs by making New Jersey the most business-friendly states, and fund and support the police. In his statements, Murphy said that hundreds of thousands of middle-class families have received tax relief, schools have gotten the funding that they need, and child care, healthcare, and college have all gotten more affordable. With the conclusion of the debates in the New Jersey gubernatorial race, it will now be in the hands of the voters as they head to the polls on November 2nd.
