---
title: "Malaria Research"
editor: visual
---

### **Building awareness and trust -- how the U.S. can support the distribution of malaria vaccines**

[**Executive Summary**]{.underline}

When a person is bit by a mosquito carrying the parasite that causes malaria, it will usually take one-four weeks for them to experience a high fever, shaking chills, extreme fatigue, or vomiting, among a host of other possible symptoms. If the case is left untreated and progresses over a few weeks, the parasite can block the blood vessels to the brain or damage necessary organs such as the kidney and liver, leading to potentially fatal brain swelling or organ failure. In 2020, while the rest of the world was fighting off the devastating impacts of COVID-19, this malaria nightmare left around 627,00 people dead in Africa.

In October of 2021, the fight against malaria was forever changed when the World Health Organization recommended the first anti-malaria vaccine to be used for children under five in Sub-Saharan Africa and other regions vulnerable to the virus. The vaccine contains a major protein from the plasmodium parasite, which is the parasite that causes malaria in humans. Essentially, introducing the protein to a person's immune system trains the body to provide an immune defense before the parasite can infect the red blood cells. So, if you're vaccinated and bit by a mosquito carrying the parasite, your immune system will likely recognize the parasite before it can do real harm to your body. The vaccine did well during its first tests in Africa. When children were given the vaccine in Ghana, Kenya, and Malawi, it cut cases by 40% and hospitalizations by one-third. Still, the relatively mild efficacy of the vaccine ensures it's not a silver bullet to ending malaria in Sub-Saharan Africa. Nonetheless, the successful distribution of the vaccine and continued research of other malaria vaccines will be the most critical step in alleviating the pain that malaria has caused.

[**Introduction**]{.underline}

In the face of the hopefulness surrounding a new vaccine, there has been a whirlwind of challenges to be faced in its rollout. To put it bluntly, it's going to be incredibly difficult to get the vaccine to every child under the age of five in a vast and complex region. This has caused many major funders, such as the Bill and Melinda Gates Foundation, who provided a considerable chunk of funding for the research of the vaccine, to back off on donating towards distribution efforts. A big win came in August of this year, when Gavi, the Vaccine Alliance and the WHO announced a funding expansion of \$160 million. However, the initial funding package seems to be only a temporary fix for what could grow into a nagging pain, like taking an Aspirin for chronic back pain. It may be okay for now, but questions will soon come on who will fund the rollout next year, let alone the decades to follow.

Researchers have suggested that the distribution and rollout of the vaccine will cost around \$325 million dollars per year across ten countries with high incidence of malaria. Without third-party funding for the rollout, the effort will be a wash as many governments in the region won't be able to get the vaccines into the hands of doctors and public health workers, leaving millions of kids unvaccinated across several countries. Another important issue is the relatively low public awareness of the vaccine. One of the largest challenges will be overcoming the cultural and regional challenges within Africa to educate individuals and communities about vaccination efforts and drive public trust in the vaccine. Many areas across the continent don't have access to basic public health resources, let alone the resources that are attainable in the U.S., where children can receive over a dozen vaccines before their first year in school. Simply showing up at a person's doorstep with a vial of liquid and a needle won't convince them that the vaccine is safe and necessary for their health.

[**Approaches and Results**]{.underline}

Funding is certainly an important issue, but it's not the money itself that will be the game-changing solution, instead the answers will come in what is done with the money. Governments and organizations can pour billions of dollars into fighting malaria in Africa over the next decades, but they may see the same results if they don't understand the people that live there.

Taiwo Aremu, a physician and clinical research specialist at the University of Minnesota Medical School, believes that governments must do a better job in confronting these specific cultural and regional challenges when rolling out vaccines. Aremu, who is originally from Nigeria, has passionately researched malaria and Covid-19 treatment and prevention across Sub-Saharan Africa over the past few years. As a graduate of University of Ilorin Medical School in Kwara State, Nigeria, the fight against infectious diseases in the region is uniquely personal to him. Most recently, he has been part of a team evaluating public awareness and trust for malaria vaccines in the region. Aremu and his team's research illustrates the vast array of issues regarding public awareness of the vaccine in Africa, showing knowledge gaps due to disparities in education, income level, and region.

Aremu's research, showing that nearly 40% of people throughout the malaria hotspots of Ghana, Nigeria, and Uganda are unaware of the vaccine, may seem bleak to many. Yet he maintains an optimistic outlook on the future of malaria vaccination efforts in Sub-Saharan Africa, and he believes that his background and familiarity with the region gives him an unparalleled perspective on the measures public health officials can take to gain the public's trust in the region. Aremu believes that one of the most important measures that can be taken is giving African governments the tools to start producing vaccines within Africa. He says that this would ease the funding burden on Western countries and simultaneously build trust and awareness of the vaccine; "right now in Africa, we do not have a viable vaccine producing company. We must start thinking about how we can encourage local production of vaccines. If vaccines are produced in Africa, then Africans will accept it, because they have trust in what has been produced by them."

While mass production of vaccines within Africa may seem far off, it is certainly in the realm of possibility. In fact, the U.S. and other Western partners provided financial assistance to African nations to build production facilities for the COVID-19 vaccine. Aremu believes that similar initiatives should be taken for the vaccine and any vaccines which will follow. In the short-term, Aremu believes that public health officials must make a conscious effort of getting local community leaders on board with the production process, "we must get governments and communities on board with production. Whether that means funding bringing them here so that they can go home and tell the media 'we've seen the vaccine, it's good and you guys should have it.' Locals want to listen to their own local people." Ultimately, Aremu says that the problem boils down to a lack of understanding of how African communities function. Many small and primarily rural communities will be resistant to the vaccine if it's produced in isolation outside of the continent, and they won't simply take an outsider's word on the safety and necessity of the vaccine.

Perhaps most significantly, Aremu says that public awareness campaigns must be restructured to target the right individuals. His team's study concluded that the most important groups to target should be women of child-bearing age and women who are integral in childcare, as by far the most vulnerable group to malaria is children under five. However, Aremu also notes that it is important to target other groups of people who may be overlooked by public health officials. Particularly, he notes the importance of those who are culturally significant in many African communities; "people listen to the elderly folks, as they make decisions for the family. Therefore, targeting the most elderly people in the family or the clan will influence others to go for it." Aremu also says that contacting religious leaders will be important in advancing efforts, given the importance of religion throughout Sub-Saharan Africa. Ultimately, if faith-based buy into the idea of distributing the malaria vaccine within their communities, then their followers will heavily increase demand for the vaccine throughout the region.

[**Conclusion and Recommendations**]{.underline}

While it is certainly true that more funding commitments are needed to effectively roll out malaria vaccines throughout Sub-Saharan Africa, how countries and public health officials allocate the funding will play the most crucial role in such an effort's success. Investments must be made to foster awareness and trust throughout the region. Experts are very optimistic that there could be a sufficient amount of malaria vaccines within the region in a matter of years, but if people choose not to take them, then the years of preparation for this moment will have been wasted. Therefore, planning and implementing outreach programs and an array of innovative approaches will be critical in the distribution effort.

Directing more funding from the U.S.'s global health budget towards localized, targeted outreach is one of the important factors in increasing public trust and awareness of the vaccine. Additionally, outreach must be culturally sensitive and adaptable, traversing through the complex differences between regions in Sub-Saharan Africa. The most effective groups to target will be important community members such as religious leaders and local government and community activists. Targeting these groups will allow public health officials to reach those in the most affected and isolated areas, particularly those of lower income and education levels, and those located in rural areas. Funding from the budget should also be adjusted to encourage local involvement in production. By involving leaders of local communities in the production process and paving the way for future production of malaria vaccines in Africa, trust will be built in the vaccine across the region, and a stronger and more equitable distribution campaign can be ensured.

[**Works Cited**]{.underline}

Aremu, Taiwo Opeyemi, et al. "Assessing Public Awareness of the Malaria Vaccine in Sub-Saharan Africa." MDPI, Multidisciplinary Digital Publishing Institute, 30 Aug. 2022, <https://www.mdpi.com/2414-6366/7/9/215>.

Beaubien, Jason. "Who Greenlights the World's First Malaria Vaccine - but It's Not a Perfect Shot." NPR, NPR, 6 Oct. 2021, <https://www.npr.org/sections/goatsandsoda/2021/10/06/1010998517/who-greenlights-the-worlds-first-malaria-vaccine-but-its-not-a-perfect-shot>.

"Breaking down the U.S. Global Health Budget by Program Area." KFF, 15 Sept. 2022, <https://www.kff.org/global-health-policy/fact-sheet/breaking-down-the-u-s-global-health-budget-by-program-area/>.

"CDC - Malaria - Malaria Worldwide - Impact of Malaria." Centers for Disease Control and Prevention, Centers for Disease Control and Prevention, 16 Dec. 2021, <https://www.cdc.gov/malaria/malaria_worldwide/impact.html>.

Egbewande, Oluwaseyi Muyiwa. "The RTS,S Malaria Vaccine: Journey from Conception to Recommendation." Public Health in Practice, Elsevier, 17 June 2022, <https://www.sciencedirect.com/science/article/pii/S2666535222000593>.

"Fact Sheet about Malaria." World Health Organization, World Health Organization, <https://www.who.int/news-room/fact-sheets/detail/malaria>.

"Gavi Opens Applications for Malaria Vaccine Rollout Support." Gavi, the Vaccine Alliance, <https://www.gavi.org/news/media-room/gavi-opens-applications-malaria-vaccine-rollout-support>.

Hassan, Abdulwasiu Oladele, et al. "Malaria Vaccine: Prospects and Challenges." Madonna University Journal of Medicine and Health Sciences, 12 July 2022, <https://madonnauniversity.edu.ng/journals/index.php/medicine/article/view/64/70>.

The Lancet. "Malaria Vaccine Approval: A Step Change for Global Health." The Lancet, Elsevier, 16 Oct. 2021, <https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)02235-2/fulltext>.

Maxmen, Amy. "Scientists Hail Historic Malaria Vaccine Approval - but Point to Challenges Ahead." Nature News, Nature Publishing Group, 8 Oct. 2021, <https://www.nature.com/articles/d41586-021-02755-5>.

"Support for Africa's Vaccine Production Is Good for the World." IMF, <https://www.imf.org/en/Blogs/Articles/2022/01/12/blog011322-support-for-africas-vaccine-production-is-good-for-the-world>.

"WHO Recommends Groundbreaking Malaria Vaccine for Children at Risk." World Health Organization, World Health Organization, <https://www.who.int/news/item/06-10-2021-who-recommends-groundbreaking-malaria-vaccine-for-children-at-risk>.
